# Generated by Django 5.2.1 on 2025-11-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('purchase', models.DateTimeField(blank=True, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('milk', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breeding', models.CharField(blank=True, max_length=100, null=True)),
                ('convincing_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('milk_day_15', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('milk_day_30', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('milk_day_60', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('milk_day_75', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('outward_date', models.DateField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salvage_date', models.DateField(blank=True, null=True)),
                ('salvage', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Critical', 'Critical')], default='Healthy', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattles', to='cows.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('female_cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_breedings', to='cows.cattle')),
                ('male_cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_breedings', to='cows.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('inward_date', models.DateField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('convincing_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('milk_day_0', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('milk_day_15', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('milk_day_30', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('milk_day_60', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('milk_day_75', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('outward_date', models.DateField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sold', models.CharField(blank=True, max_length=50, null=True)),
                ('salvage_date', models.DateField(blank=True, null=True)),
                ('salvage', models.CharField(blank=True, max_length=50, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='cows.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateField(auto_created=True)),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='Quantity in kg/litre')),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='cows.batch')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='cows.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Critical', 'Critical')], default='Healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cows.batch')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cows.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(auto_created=True)),
                ('amount', models.FloatField()),
                ('source', models.CharField(help_text='e.g., Milk Sale, Animal Sale, Others', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='cows.batch')),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='cows.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Milking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milkings', to='cows.cattle')),
            ],
        ),
    ]
