# Generated by Django 5.2.1 on 2025-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
