# Generated by Django 5.2.1 on 2025-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0002_alter_cattle_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='milking',
            name='milk_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
