# Generated by Django 5.2.1 on 2025-11-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_milking_milk_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='breeding',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Inseminated', 'Inseminated'), ('Pregnant', 'Pregnant'), ('Dry', 'Dry')], max_length=20),
        ),
    ]
