# Generated by Django 5.2.1 on 2025-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0004_alter_cattle_breeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='reentered',
            field=models.BooleanField(default=False),
        ),
    ]
