# Generated by Django 5.2.1 on 2025-12-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0006_medicine_medicineinventory_medicineusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineusage',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicineusage',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='medicineusage',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='medicineusage',
            name='cattle',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='MedicineInventory',
        ),
        migrations.DeleteModel(
            name='MedicineUsage',
        ),
    ]
