# Generated by Django 5.2.1 on 2025-12-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0008_medicine_medicineinventory_medicineusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineinventory',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='category',
            field=models.CharField(choices=[('Vaccine', 'Vaccine'), ('Antibiotic', 'Antibiotic'), ('Antiseptic', 'Antiseptic'), ('Vitamin', 'Vitamin')], default='Antibiotic', max_length=20),
        ),
    ]
