# Generated by Django 5.2.1 on 2025-12-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0009_remove_medicineinventory_batch_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
    ]
