# Generated by Django 5.2.1 on 2025-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0010_remove_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineinventory',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='batch_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
