# Generated by Django 5.2.1 on 2025-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymilk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkcollection',
            name='fat',
        ),
    ]
