# Generated by Django 5.2.1 on 2025-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymilk', '0002_remove_milkcollection_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='cardno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
