# Generated by Django 5.2.8 on 2025-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymilk', '0003_farmer_address_farmer_cardno_farmer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='cardno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='payment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
