# Generated by Django 5.2.8 on 2025-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymilk', '0004_milkcollection_cardno_milkcollection_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='farmer',
            field=models.CharField(max_length=100),
        ),
    ]
