# Generated by Django 5.2.1 on 2025-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('pcs', 'Pieces')], default='liter', max_length=10),
        ),
    ]
