# Generated by Django 5.2.1 on 2025-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
