# Generated by Django 5.2.1 on 2025-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
