# Generated by Django 5.2.1 on 2025-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_billitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter')], default='liter', max_length=10),
        ),
    ]
