# Generated by Django 5.2.1 on 2025-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_billitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='cardno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='payment',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
